version: '3.2'

services:
  web:
    build: .
    command:  python manage.py runserver 0.0.0.0:8005
    volumes:
      - .:/usr/src/app/
    ports:
      - 8005:8005
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=messaging
      - POSTGRES_PASSWORD=messaging
      - POSTGRES_DB=messaging

volumes:
  postgres_data:
