# Generated by Django 5.0.1 on 2024-01-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_chats_customer_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
    ]
