# Generated by Django 5.0.1 on 2024-01-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_rename_message_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customers',
        ),
    ]
